
// Generated by source_obfuscator.py. Do not edit manually.
// String protection: aes256-gcm-bundle-blob-hmac-index-v4
import Foundation
import CryptoKit

enum AnIIRyTZZzTxkmgiDVYoJSk {
    private static let material: [UInt8] = {
        let first: [UInt8] = [62, 50, 209, 113, 249, 176, 67, 109, 28, 164, 47, 12, 225, 205, 108, 22, 31, 96, 153, 226, 107, 164, 148, 123, 85, 67, 233, 99, 113, 209, 145, 50]
        let second: [UInt8] = [36, 89, 7, 232, 2, 228, 165, 70, 63, 188, 182, 68, 42, 80, 154, 243, 114, 231, 139, 143, 149, 210, 233, 41, 82, 238, 7, 15, 172, 30, 18, 185]
        let order: [Int] = [20, 19, 1, 15, 6, 16, 3, 26, 12, 29, 28, 22, 7, 0, 31, 8, 13, 24, 9, 27, 17, 25, 4, 11, 2, 10, 5, 18, 30, 14, 21, 23]
        return (0..<32).map { first[order[$0]] &+ second[$0] }
    }()
    private static let blob: Data? = Bundle.main.url(forResource: "\u{53}\u{74}\u{6f}\u{73}\u{67}\u{4d}\u{75}\u{51}\u{68}\u{74}\u{61}\u{74}\u{48}\u{6d}\u{53}\u{6c}\u{69}\u{54}\u{56}\u{52}", withExtension: "\u{64}\u{61}\u{74}").flatMap { try? Data(contentsOf: $0) }
    private static let magic = [UInt8]([83, 79, 66, 52])

    private static func u16(_ data: Data, _ offset: Int) -> Int? {
        guard offset >= 0, offset + 2 <= data.count else { return nil }
        return Int(data[offset]) | (Int(data[offset + 1]) << 8)
    }
    private static func u32(_ data: Data, _ offset: Int) -> Int? {
        guard offset >= 0, offset + 4 <= data.count else { return nil }
        return Int(data[offset]) | (Int(data[offset + 1]) << 8) | (Int(data[offset + 2]) << 16) | (Int(data[offset + 3]) << 24)
    }
    private static func route(_ identifier: String) -> [UInt8] {
        let key = SymmetricKey(data: Data(material))
        return Array(HMAC<SHA256>.authenticationCode(for: Data("\u{62}\u{6c}\u{6f}\u{62}\u{2d}\u{72}\u{6f}\u{75}\u{74}\u{65}\u{2d}\u{76}\u{34}\0".utf8) + Data(identifier.utf8), using: key).prefix(16))
    }
    static func dVYoJSkgSwBacunjUDdEpA(_ identifier: String) -> String {
        guard let data = blob, data.count >= 20,
              Array(data[0..<4]) == magic, u16(data, 4) == 4,
              let count = u32(data, 8), let indexOffset = u32(data, 12), let payloadOffset = u32(data, 16),
              indexOffset >= 20, payloadOffset >= indexOffset, payloadOffset <= data.count,
              count <= (payloadOffset - indexOffset) / 24 else { return "" }
        let wanted = route(identifier)
        var cursor = indexOffset
        for _ in 0..<count {
            guard cursor + 24 <= payloadOffset,
                  let relative = u32(data, cursor + 16), let length = u32(data, cursor + 20),
                  relative <= data.count - payloadOffset, length <= data.count - payloadOffset - relative else { return "" }
            if Array(data[cursor..<cursor + 16]) == wanted {
                let start = payloadOffset + relative
                let combined = data.subdata(in: start..<start + length)
                let key = SymmetricKey(data: Data(material))
                guard let box = try? AES.GCM.SealedBox(combined: combined),
                      let plain = try? AES.GCM.open(box, using: key, authenticating: Data(identifier.utf8)) else { return "" }
                return String(data: plain, encoding: .utf8) ?? ""
            }
            cursor += 24
        }
        return ""
    }
}

@objc(UddEpAuUjwFdDpyz)
final class _UddEpAuUjwFdDpyz: NSObject {
    @objc(lHdeeneANaBNoVHKANIIRyT:)
    static func lHdeeneANaBNoVHKANIIRyT(_ identifier: NSString) -> NSString { AnIIRyTZZzTxkmgiDVYoJSk.dVYoJSkgSwBacunjUDdEpA(identifier as String) as NSString }
}
// End generated string protection.







import SwiftUI

struct HzttuEEeHuFk: View {

    @ObservedObject private var channelStore = ZkTBoxQKDTQFRnK.shared
    
    @State private var input = ""
    @State private var showFeature = false
    @State private var errorMessage: String?
    @FocusState private var isFieldFocused: Bool

    var body: some View {
        
        nHTKJEVMahyAwig()
    }

    

    

    
    @ViewBuilder
    @inline(never)
    private func nHTKJEVMahyAwig() -> some View {
        // source-obfuscator:padding:v1
        let _ = Self.nPzoooEIOPdbDVuGYhQ()

        pEotPbqhMcSsczCIOn
    }

    @ViewBuilder
    private var pEotPbqhMcSsczCIOn: some View {
        VStack(spacing: 16) {
            wXXntAHOTypRman

            TextField("", text: $input)
                .keyboardType(.default)
                .textFieldStyle(.roundedBorder)
                .focused($isFieldFocused)
                .multilineTextAlignment(.center)
                .frame(maxWidth: 240)

            aVSGxmzChtTfUKMRB

            if let errorMessage {
                Text(errorMessage)
                    .font(.footnote)
                    .foregroundColor(.red)
            }

            eWyQJJhsfsqp
        }
        .padding()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color.white.ignoresSafeArea())
        .onTapGesture {
            isFieldFocused = false
        }
        .onAppear {
            if let saved = channelStore.channel {
                input = saved
            }
        }
    }


    @ViewBuilder
    private var wXXntAHOTypRman: some View {
        Text("")
                .font(.headline)
    }

    @ViewBuilder
    private var aVSGxmzChtTfUKMRB: some View {
        Button("") {
                isFieldFocused = false
                bVrbnlFRLxyaLSM()
            }
            .buttonStyle(.borderedProminent)
            .disabled(normalizedInput.isEmpty)
    }

    @ViewBuilder
    private var eWyQJJhsfsqp: some View {
        NavigationLink(
                destination: VjQVDhcMRYSyyRS(channel: normalizedInput),
                isActive: $showFeature
            ) {
                EmptyView()
            }
            .hidden()
    }

    // source-obfuscator:padding:v1
    @inline(never)
    private nonisolated static func nPzoooEIOPdbDVuGYhQ() -> String {
        let token = "\u{37}\u{30}\u{34}\u{35}\u{32}\u{62}\u{65}\u{38}\u{31}\u{38}\u{30}\u{63}\u{33}\u{65}\u{38}\u{39}\u{37}\u{33}\u{36}\u{65}\u{39}\u{64}\u{35}\u{31}"
        let values = [5, 10, 25, 22]
        let folded = values.map { ($0 * 5 + 13) % 97 }.filter { $0 % 2 != 0 }.reduce(0, +)
        let base = folded
        let width = (base) % 17
        let score = (width + 5) * 5
        if score > 24 { return String(token.prefix(12)) + String(score % 31) }
        return token + "\u{2d}" + String(score)
    }
}

struct VjQVDhcMRYSyyRS: View {
    let channel: String

    var body: some View {
        // source-obfuscator:padding:v1
        let _ = Self.bHOgYptjTmgDLHWyS()

        VStack {
            Text("")
        }
        .navigationBarTitleDisplayMode(.inline)
    }

    // source-obfuscator:padding:v1
    @inline(never)
    private nonisolated static func bHOgYptjTmgDLHWyS() -> String {
        let source = "\u{31}\u{36}\u{35}\u{30}\u{37}\u{61}\u{66}\u{30}\u{61}\u{63}\u{63}\u{33}\u{30}\u{39}\u{38}\u{31}\u{31}\u{30}\u{30}\u{37}\u{33}\u{31}\u{39}\u{34}\u{2d}\u{31}\u{38}"
        let checksum = source.unicodeScalars.reduce(0) { ($0 * 33 + Int($1.value)) % 997 }
        let base = checksum
        let width = (base) % 17
        let score = (width + 18) * 8
        let token = "\u{31}\u{36}\u{35}\u{30}\u{37}\u{61}\u{66}\u{30}\u{61}\u{63}\u{63}\u{33}\u{30}\u{39}\u{38}\u{31}\u{31}\u{30}\u{30}\u{37}\u{33}\u{31}\u{39}\u{34}"
        var result = String(score) + token
        if score % 2 == 0 {
            result = token + String(score)
        }
        return result
    }
}



extension HzttuEEeHuFk {
    private func bVrbnlFRLxyaLSM() {
        
        guard channelStore.yKaCBSkkRdVGrZELtuKu(normalizedInput) else {
            errorMessage = AnIIRyTZZzTxkmgiDVYoJSk.dVYoJSkgSwBacunjUDdEpA("\u{73}\u{49}\u{65}\u{4f}\u{5a}\u{4a}\u{35}\u{38}\u{33}\u{54}")
            return
        }
        channelStore.pWHhutoTvaTt(normalizedInput)
        
        errorMessage = nil
        showFeature = true
    }

    private var normalizedInput: String {
        input.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
