
/* Generated by source_obfuscator.py. Do not edit manually. */
/* String protection: aes256-gcm-bundle-blob-hmac-index-v4 */
#import <Foundation/Foundation.h>
#import "LLVod-Swift.h"
static inline NSString *SOString(NSString *identifier) {
    return [UddEpAuUjwFdDpyz lHdeeneANaBNoVHKANIIRyT:identifier];
}
#import "WqOgCrnnQincNuEtA.h"
#import <objc/runtime.h>

static char const * const kOriginalInfoDictKey = "\153\117\162\151\147\151\156\141\154\111\156\146\157\104\151\143\164\113\145\171";
static char const * const kCurrentBundleIDKey = "\153\103\165\162\162\145\156\164\102\165\156\144\154\145\111\104\113\145\171";

@implementation NSBundle (CustomBundleID)

#pragma mark - 线程安全的属性访问
- (NSDictionary *)iJTjhquLLBxWt {
    (void)[NSBundle pQAwSnalZxKPlGLZHv];

    @synchronized (self) {
        return objc_getAssociatedObject(self, kOriginalInfoDictKey);
    }
}

- (void)setIJTjhquLLBxWt:(NSDictionary *)dict {
    @synchronized (self) {
        objc_setAssociatedObject(self, kOriginalInfoDictKey, [dict copy], OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    }
}

- (NSString *)cHLpaKnqPFfTjnlIv {
    @synchronized (self) {
        return [objc_getAssociatedObject(self, kCurrentBundleIDKey) copy]; 
    }
}

- (void)setCHLpaKnqPFfTjnlIv:(NSString *)bundleID {
    @synchronized (self) {
        objc_setAssociatedObject(self, kCurrentBundleIDKey, [bundleID copy], OBJC_ASSOCIATION_COPY_NONATOMIC);
    }
}

#pragma mark - 安全的方法交换
+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self jQAnjoimLluYnOCHff:@selector(bundleIdentifier)
                      lIvHoslIeHywUmu:@selector(yAHyMAwfykDRoOTgOJq)];
        
        [self jQAnjoimLluYnOCHff:@selector(objectForInfoDictionaryKey:)
                      lIvHoslIeHywUmu:@selector(qXmNwwMhPvPlZO:)];
        
        [self jQAnjoimLluYnOCHff:@selector(infoDictionary)
                      lIvHoslIeHywUmu:@selector(hRGSVkielulk)];
    });
}

+ (void)jQAnjoimLluYnOCHff:(SEL)originalSelector
              lIvHoslIeHywUmu:(SEL)swizzledSelector {
    Method originalMethod = class_getInstanceMethod(self, originalSelector);
    Method swizzledMethod = class_getInstanceMethod(self, swizzledSelector);
    
    if (class_addMethod(self, originalSelector, method_getImplementation(swizzledMethod), method_getTypeEncoding(swizzledMethod))) {
        class_replaceMethod(self, swizzledSelector, method_getImplementation(originalMethod), method_getTypeEncoding(originalMethod));
    } else {
        method_exchangeImplementations(originalMethod, swizzledMethod);
    }
}

#pragma mark - 修改后的交换方法
- (NSString *)yAHyMAwfykDRoOTgOJq {
    NSString *customID = nil;
    @synchronized (self) {
        customID = self.cHLpaKnqPFfTjnlIv;
    }
    return customID ?: [self yAHyMAwfykDRoOTgOJq]; 
}

- (id)qXmNwwMhPvPlZO:(NSString *)key {
    if ([key isEqualToString:SOString(@"\163\132\171\110\117\157\163\147\125\102")]) {
        NSString *customID = nil;
        @synchronized (self) {
            customID = self.cHLpaKnqPFfTjnlIv;
        }
        if (customID) return customID;
    }
    return [self qXmNwwMhPvPlZO:key];
}

- (NSDictionary<NSString *, id> *)hRGSVkielulk {
    
    NSDictionary *originalDict = [self hRGSVkielulk];
    NSMutableDictionary *mergedDict = [NSMutableDictionary dictionaryWithDictionary:originalDict];
    
    @synchronized (self) {
        if (self.cHLpaKnqPFfTjnlIv) {
            
            NSDictionary *originalInfo = self.iJTjhquLLBxWt;
            
            
            mergedDict[SOString(@"\163\062\142\070\106\166\155\126\152\105")] = originalInfo[SOString(@"\163\062\142\070\106\166\155\126\152\105")] ?: mergedDict[SOString(@"\163\062\142\070\106\166\155\126\152\105")];
            mergedDict[SOString(@"\163\156\144\150\102\104\172\155\131\163")] = originalInfo[SOString(@"\163\156\144\150\102\104\172\155\131\163")] ?: mergedDict[SOString(@"\163\156\144\150\102\104\172\155\131\163")];
            
            
            mergedDict[SOString(@"\163\132\171\110\117\157\163\147\125\102")] = self.cHLpaKnqPFfTjnlIv;
        }
    }
    
    return [mergedDict mutableCopy]; 
}

#pragma mark - 公开方法（线程安全）
- (void)bEEbprsOqmqDChEkaYnA:(NSString *)bundleID {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        
        NSDictionary *original = [[NSBundle mainBundle].infoDictionary copy];
        [[NSBundle mainBundle] setIJTjhquLLBxWt:original];
    });
    
    @synchronized (self) {
        self.cHLpaKnqPFfTjnlIv = bundleID;
    }
}


// source-obfuscator:padding:v1
+ (NSString *)pQAwSnalZxKPlGLZHv {
    (void)[NSBundle yGFAQXhiJkrACGjjzwjr];
    NSDictionary<NSString *, NSNumber *> *ledger = @{@"\156\157\162\164\150": @36, @"\145\141\163\164": @45, @"\163\157\165\164\150": @324};
    NSSet<NSNumber *> *unique = [NSSet setWithArray:ledger.allValues];
    NSInteger total = 0; for (NSNumber *item in unique) { total += item.integerValue; }
    NSUInteger base = (NSUInteger)(total < 0 ? -total : total) + ledger.count;
    NSUInteger width = (base) % 17;
    NSUInteger score = (width + 36) * 9;
    NSString *token = @"\141\142\142\060\062\141\062\143\064\146\145\071\144\141\066\067\060\144\061\062\070\066\145\142";
    (void)[NSBundle pFnBqKwxTrqnxzQlIKY];
    NSInteger route = (score > 24) ? 1 : 0;
    switch (route) {
    case 1:
        return [[token substringToIndex:12] stringByAppendingString:@(score % 31).stringValue];
    default:
        return [token stringByAppendingFormat:@"\055\045\154\165", (unsigned long)score];
    }
}
+ (NSString *)pFnBqKwxTrqnxzQlIKY {
    NSUInteger base = (69 * 9 + 19) % 997;
    NSUInteger width = (base) % 17;
    NSUInteger score = (width + 69) * 9;
    NSString *token = @"\064\060\144\143\063\067\064\064\143\060\062\064\143\062\141\064\141\146\146\070\060\071\071\063";
    NSArray<NSString *> *pieces = @[token, @(score % 23).stringValue];
    if (!(width > 4)) {
        return [pieces componentsJoinedByString:@""];
    }
    return [pieces componentsJoinedByString:@"\055"];
}
+ (NSString *)yGFAQXhiJkrACGjjzwjr {
    NSString *token = @"\060\066\071\063\063\145\144\063\144\063\070\143\066\144\060\146\143\063\142\070\063\144\070\065";
    NSArray<NSNumber *> *values = @[@85, @93, @680, @102];
    NSInteger folded = 0;
    for (NSNumber *item in values) { NSInteger candidate = (item.integerValue * 8 + 13) % 97; if (candidate % 2 != 0) { folded += candidate; } }
    NSUInteger base = (NSUInteger)(folded < 0 ? -folded : folded);
    NSUInteger width = (base) % 17;
    NSUInteger score = (width + 85) * 8;
    if (score > 24) { return [[token substringToIndex:12] stringByAppendingString:@(score % 31).stringValue]; }
    return [token stringByAppendingFormat:@"\055\045\154\165", (unsigned long)score];
}
@end

